import { getDb, saveDb } from '../src/lib/db';
import bcrypt from 'bcrypt';
import { v4 as uuidv4 } from 'uuid';
import { User, CropListing } from '../src/types/user';

async function seedDemoData() {
  const db = await getDb();

  // Clear existing data
  db.data.users = [];
  db.data.cropListings = [];

  const farmers: User[] = [
    {
      id: uuidv4(),
      email: 'john.kamau@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'John Kamau',
      role: 'farmer',
      phone: '+254712345001',
      location: 'Nakuru',
      bio: 'Experienced maize and wheat farmer with 15 years of experience',
      avatar: '/images/farmers/john_kamau.jpg',
      isVerified: true,
      verifiedAt: new Date('2025-01-15'),
      createdAt: new Date('2024-12-01'),
      updatedAt: new Date('2025-01-15'),
    },
    {
      id: uuidv4(),
      email: 'mary.wanjiku@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Mary Wanjiku',
      role: 'farmer',
      phone: '+254712345002',
      location: 'Murang\'a',
      bio: 'Organic farming specialist - vegetables and fruits',
      avatar: '/images/farmers/mary_wanjiku.jpg',
      isVerified: true,
      verifiedAt: new Date('2025-01-18'),
      createdAt: new Date('2024-12-05'),
      updatedAt: new Date('2025-01-18'),
    },
    {
      id: uuidv4(),
      email: 'peter.omondi@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Peter Omondi',
      role: 'farmer',
      phone: '+254712345003',
      location: 'Kisumu',
      bio: 'Fish farming and rice cultivation specialist',
      avatar: '/images/farmers/peter_omondi.jpg',
      isVerified: true,
      verifiedAt: new Date('2025-01-20'),
      createdAt: new Date('2024-12-10'),
      updatedAt: new Date('2025-01-20'),
    },
    {
      id: uuidv4(),
      email: 'grace.akinyi@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Grace Akinyi',
      role: 'farmer',
      phone: '+254712345004',
      location: 'Kisii',
      bio: 'Banana and coffee grower',
      avatar: '/images/farmers/grace_akinyi.jpg',
      isVerified: true,
      verifiedAt: new Date('2025-01-22'),
      createdAt: new Date('2024-12-15'),
      updatedAt: new Date('2025-01-22'),
    },
    {
      id: uuidv4(),
      email: 'david.kipchoge@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'David Kipchoge',
      role: 'farmer',
      phone: '+254712345005',
      location: 'Eldoret',
      bio: 'Large scale grain producer',
      avatar: '/images/farmers/david_kipchoge.jpg',
      isVerified: true,
      verifiedAt: new Date('2025-01-25'),
      createdAt: new Date('2024-12-20'),
      updatedAt: new Date('2025-01-25'),
    },
    {
      id: uuidv4(),
      email: 'sarah.muthoni@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Sarah Muthoni',
      role: 'farmer',
      phone: '+254712345006',
      location: 'Nyandarua',
      bio: 'Irish potato specialist',
      avatar: '/images/farmers/sarah_muthoni.jpg',
      isVerified: true,
      verifiedAt: new Date('2025-01-28'),
      createdAt: new Date('2025-01-01'),
      updatedAt: new Date('2025-01-28'),
    },
    {
      id: uuidv4(),
      email: 'james.mutua@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'James Mutua',
      role: 'farmer',
      phone: '+254712345007',
      location: 'Machakos',
      bio: 'Certified seed producer',
      avatar: '/images/farmers/james_mutua.jpg',
      isVerified: false,
      createdAt: new Date('2025-01-05'),
      updatedAt: new Date('2025-01-05'),
    },
    {
      id: uuidv4(),
      email: 'lucy.njeri@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Lucy Njeri',
      role: 'farmer',
      phone: '+254712345008',
      location: 'Kakamega',
      bio: 'Sugarcane and groundnut farmer',
      avatar: '/images/farmers/lucy_njeri.jpg',
      isVerified: false,
      createdAt: new Date('2025-01-10'),
      updatedAt: new Date('2025-01-10'),
    },
    {
      id: uuidv4(),
      email: 'daniel.kimani@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Daniel Kimani',
      role: 'farmer',
      phone: '+254712345009',
      location: 'Kiambu',
      bio: 'Coffee and tea grower',
      avatar: '/images/farmers/daniel_kimani.jpg',
      isVerified: false,
      createdAt: new Date('2025-01-12'),
      updatedAt: new Date('2025-01-12'),
    },
    {
      id: uuidv4(),
      email: 'esther.wangari@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Esther Wangari',
      role: 'farmer',
      phone: '+254712345010',
      location: 'Embu',
      bio: 'Mixed farming - dairy and crops',
      avatar: '/images/farmers/esther_wangari.jpg',
      isVerified: false,
      createdAt: new Date('2025-01-15'),
      updatedAt: new Date('2025-01-15'),
    },
  ];

  const cropListings: CropListing[] = [
    // John Kamau's listings
    {
      id: uuidv4(),
      farmerId: farmers[0].id,
      farmerName: farmers[0].name,
      cropName: 'Maize',
      quantity: 100,
      unit: 'bags',
      pricePerUnit: 3500,
      description: 'High-quality yellow maize, properly dried and stored. Suitable for both animal feed and human consumption. Delivery available within Nakuru.',
      location: 'Nakuru',
      datePosted: new Date('2025-01-28'),
      status: 'available',
      image: '/images/farming/maize.jpg',
      createdAt: new Date('2025-01-28'),
      updatedAt: new Date('2025-01-28'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[0].id,
      farmerName: farmers[0].name,
      cropName: 'Wheat',
      quantity: 50,
      unit: 'bags',
      pricePerUnit: 4200,
      description: 'Premium wheat grain, freshly harvested. Perfect for milling. Meets KEBS standards.',
      location: 'Nakuru',
      datePosted: new Date('2025-01-25'),
      status: 'available',
      image: '/images/farming/wheat.jpg',
      createdAt: new Date('2025-01-25'),
      updatedAt: new Date('2025-01-25'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[0].id,
      farmerName: farmers[0].name,
      cropName: 'Beans (Red Kidney)',
      quantity: 30,
      unit: 'bags',
      pricePerUnit: 5500,
      description: 'Organic red kidney beans, clean and ready for market. Excellent quality.',
      location: 'Nakuru',
      datePosted: new Date('2025-01-20'),
      status: 'sold',
      image: '/images/farming/beans.jpg',
      createdAt: new Date('2025-01-20'),
      updatedAt: new Date('2025-01-29'),
    },

    // Mary Wanjiku's listings
    {
      id: uuidv4(),
      farmerId: farmers[1].id,
      farmerName: farmers[1].name,
      cropName: 'Tomatoes',
      quantity: 500,
      unit: 'kg',
      pricePerUnit: 80,
      description: 'Fresh organic tomatoes, harvested daily. No chemicals used. Perfect for restaurants and hotels.',
      location: 'Murang\'a',
      datePosted: new Date('2025-02-01'),
      status: 'available',
      image: '/images/farming/tomatoes.jpg',
      createdAt: new Date('2025-02-01'),
      updatedAt: new Date('2025-02-01'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[1].id,
      farmerName: farmers[1].name,
      cropName: 'Cabbage',
      quantity: 200,
      unit: 'kg',
      pricePerUnit: 35,
      description: 'Fresh cabbages, organically grown. Large heads, crisp and healthy.',
      location: 'Murang\'a',
      datePosted: new Date('2025-01-30'),
      status: 'available',
      image: '/images/farming/cabbage.jpg',
      createdAt: new Date('2025-01-30'),
      updatedAt: new Date('2025-01-30'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[1].id,
      farmerName: farmers[1].name,
      cropName: 'Carrots',
      quantity: 150,
      unit: 'kg',
      pricePerUnit: 60,
      description: 'Premium carrots, sweet and crunchy. Perfect size and color.',
      location: 'Murang\'a',
      datePosted: new Date('2025-01-29'),
      status: 'available',
      image: '/images/farming/carrots.jpg',
      createdAt: new Date('2025-01-29'),
      updatedAt: new Date('2025-01-29'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[1].id,
      farmerName: farmers[1].name,
      cropName: 'Bananas',
      quantity: 300,
      unit: 'kg',
      pricePerUnit: 50,
      description: 'Sweet cooking bananas (matoke) and dessert bananas available. Freshly harvested.',
      location: 'Murang\'a',
      datePosted: new Date('2025-01-27'),
      status: 'available',
      image: '/images/farming/bananas.jpg',
      createdAt: new Date('2025-01-27'),
      updatedAt: new Date('2025-01-27'),
    },

    // Peter Omondi's listings
    {
      id: uuidv4(),
      farmerId: farmers[2].id,
      farmerName: farmers[2].name,
      cropName: 'Rice',
      quantity: 80,
      unit: 'bags',
      pricePerUnit: 6500,
      description: 'Premium rice from Kano Plains. Well-polished and clean. Bulk orders welcome.',
      location: 'Kisumu',
      datePosted: new Date('2025-02-02'),
      status: 'available',
      image: '/images/farming/rice.jpg',
      createdAt: new Date('2025-02-02'),
      updatedAt: new Date('2025-02-02'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[2].id,
      farmerName: farmers[2].name,
      cropName: 'Tilapia (Fresh)',
      quantity: 500,
      unit: 'kg',
      pricePerUnit: 350,
      description: 'Fresh tilapia from fish ponds. Healthy and well-fed. Can deliver chilled.',
      location: 'Kisumu',
      datePosted: new Date('2025-02-01'),
      status: 'available',
      image: '/images/farming/tilapia.jpg',
      createdAt: new Date('2025-02-01'),
      updatedAt: new Date('2025-02-01'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[2].id,
      farmerName: farmers[2].name,
      cropName: 'Sweet Potatoes',
      quantity: 200,
      unit: 'kg',
      pricePerUnit: 45,
      description: 'Orange-fleshed sweet potatoes, rich in vitamin A. Great for baking and boiling.',
      location: 'Kisumu',
      datePosted: new Date('2025-01-29'),
      status: 'available',
      image: '/images/farming/sweet_potatoes.jpg',
      createdAt: new Date('2025-01-29'),
      updatedAt: new Date('2025-01-29'),
    },

    // Grace Akinyi's listings
    {
      id: uuidv4(),
      farmerId: farmers[3].id,
      farmerName: farmers[3].name,
      cropName: 'Bananas (Matoke)',
      quantity: 400,
      unit: 'kg',
      pricePerUnit: 55,
      description: 'Premium matoke bananas from Kisii highlands. Perfect for cooking.',
      location: 'Kisii',
      datePosted: new Date('2025-02-03'),
      status: 'available',
      image: '/images/farming/bananas.jpg',
      createdAt: new Date('2025-02-03'),
      updatedAt: new Date('2025-02-03'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[3].id,
      farmerName: farmers[3].name,
      cropName: 'Coffee (Green Beans)',
      quantity: 100,
      unit: 'kg',
      pricePerUnit: 450,
      description: 'High-grade Arabica coffee beans. Properly processed and dried. AA grade quality.',
      location: 'Kisii',
      datePosted: new Date('2025-02-02'),
      status: 'available',
      image: '/images/farming/coffee.jpg',
      createdAt: new Date('2025-02-02'),
      updatedAt: new Date('2025-02-02'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[3].id,
      farmerName: farmers[3].name,
      cropName: 'Avocados',
      quantity: 300,
      unit: 'kg',
      pricePerUnit: 120,
      description: 'Hass avocados, export quality. Perfect ripeness for local and export markets.',
      location: 'Kisii',
      datePosted: new Date('2025-01-31'),
      status: 'sold',
      image: '/images/farming/avocados.jpg',
      createdAt: new Date('2025-01-31'),
      updatedAt: new Date('2025-02-03'),
    },

    // David Kipchoge's listings
    {
      id: uuidv4(),
      farmerId: farmers[4].id,
      farmerName: farmers[4].name,
      cropName: 'Maize',
      quantity: 500,
      unit: 'bags',
      pricePerUnit: 3300,
      description: 'Bulk maize supply available. Grade 1 quality, moisture content below 13.5%. Large orders welcome.',
      location: 'Eldoret',
      datePosted: new Date('2025-02-04'),
      status: 'available',
      image: '/images/farming/maize.jpg',
      createdAt: new Date('2025-02-04'),
      updatedAt: new Date('2025-02-04'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[4].id,
      farmerName: farmers[4].name,
      cropName: 'Beans (Mixed)',
      quantity: 100,
      unit: 'bags',
      pricePerUnit: 5800,
      description: 'Quality beans mix - suitable for wholesale. Cleaned and sorted.',
      location: 'Eldoret',
      datePosted: new Date('2025-02-03'),
      status: 'available',
      image: '/images/farming/beans.jpg',
      createdAt: new Date('2025-02-03'),
      updatedAt: new Date('2025-02-03'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[4].id,
      farmerName: farmers[4].name,
      cropName: 'Sorghum',
      quantity: 50,
      unit: 'bags',
      pricePerUnit: 3800,
      description: 'Gadam sorghum variety. Good for brewing and animal feed.',
      location: 'Eldoret',
      datePosted: new Date('2025-02-01'),
      status: 'available',
      image: '/images/farming/sorghum.jpg',
      createdAt: new Date('2025-02-01'),
      updatedAt: new Date('2025-02-01'),
    },

    // Sarah Muthoni's listings
    {
      id: uuidv4(),
      farmerId: farmers[5].id,
      farmerName: farmers[5].name,
      cropName: 'Irish Potatoes',
      quantity: 300,
      unit: 'bags',
      pricePerUnit: 2500,
      description: 'Fresh Irish potatoes from Nyandarua highlands. Variety: Shangi. Excellent for chips and cooking.',
      location: 'Nyandarua',
      datePosted: new Date('2025-02-04'),
      status: 'available',
      image: '/images/farming/potatoes.jpg',
      createdAt: new Date('2025-02-04'),
      updatedAt: new Date('2025-02-04'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[5].id,
      farmerName: farmers[5].name,
      cropName: 'Peas (Green)',
      quantity: 100,
      unit: 'kg',
      pricePerUnit: 150,
      description: 'Fresh green peas, perfect for cooking. Harvested this morning.',
      location: 'Nyandarua',
      datePosted: new Date('2025-02-03'),
      status: 'available',
      image: '/images/farming/peas.jpg',
      createdAt: new Date('2025-02-03'),
      updatedAt: new Date('2025-02-03'),
    },

    // James Mutua's listings (unverified)
    {
      id: uuidv4(),
      farmerId: farmers[6].id,
      farmerName: farmers[6].name,
      cropName: 'Green Grams',
      quantity: 50,
      unit: 'bags',
      pricePerUnit: 8500,
      description: 'Certified seed green grams. High germination rate. Suitable for dry areas.',
      location: 'Machakos',
      datePosted: new Date('2025-02-02'),
      status: 'available',
      image: '/images/farming/green_grams.jpg',
      createdAt: new Date('2025-02-02'),
      updatedAt: new Date('2025-02-02'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[6].id,
      farmerName: farmers[6].name,
      cropName: 'Cowpeas',
      quantity: 40,
      unit: 'bags',
      pricePerUnit: 7200,
      description: 'Quality cowpeas (kunde). Drought-resistant variety.',
      location: 'Machakos',
      datePosted: new Date('2025-02-01'),
      status: 'available',
      image: '/images/farming/cowpeas.jpg',
      createdAt: new Date('2025-02-01'),
      updatedAt: new Date('2025-02-01'),
    },

    // Lucy Njeri's listings (unverified)
    {
      id: uuidv4(),
      farmerId: farmers[7].id,
      farmerName: farmers[7].name,
      cropName: 'Groundnuts',
      quantity: 60,
      unit: 'bags',
      pricePerUnit: 9500,
      description: 'Red valencia groundnuts. Well-dried and shelled. Ready for processing.',
      location: 'Kakamega',
      datePosted: new Date('2025-02-03'),
      status: 'available',
      image: '/images/farming/groundnuts.jpg',
      createdAt: new Date('2025-02-03'),
      updatedAt: new Date('2025-02-03'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[7].id,
      farmerName: farmers[7].name,
      cropName: 'Sugarcane',
      quantity: 1000,
      unit: 'pieces',
      pricePerUnit: 80,
      description: 'Fresh sugarcane for chewing or juice extraction. Sweet variety.',
      location: 'Kakamega',
      datePosted: new Date('2025-02-02'),
      status: 'available',
      image: '/images/farming/sugarcane.jpg',
      createdAt: new Date('2025-02-02'),
      updatedAt: new Date('2025-02-02'),
    },

    // Daniel Kimani's listings (unverified)
    {
      id: uuidv4(),
      farmerId: farmers[8].id,
      farmerName: farmers[8].name,
      cropName: 'Tea Leaves (Green)',
      quantity: 500,
      unit: 'kg',
      pricePerUnit: 45,
      description: 'Fresh tea leaves from Kiambu. Ready for processing. First harvest.',
      location: 'Kiambu',
      datePosted: new Date('2025-02-04'),
      status: 'available',
      image: '/images/farming/tea.jpg',
      createdAt: new Date('2025-02-04'),
      updatedAt: new Date('2025-02-04'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[8].id,
      farmerName: farmers[8].name,
      cropName: 'Macadamia Nuts',
      quantity: 200,
      unit: 'kg',
      pricePerUnit: 300,
      description: 'Premium macadamia nuts in shell. Export quality.',
      location: 'Kiambu',
      datePosted: new Date('2025-02-03'),
      status: 'sold',
      image: '/images/farming/macadamia.jpg',
      createdAt: new Date('2025-02-03'),
      updatedAt: new Date('2025-02-04'),
    },

    // Esther Wangari's listings (unverified)
    {
      id: uuidv4(),
      farmerId: farmers[9].id,
      farmerName: farmers[9].name,
      cropName: 'Milk (Fresh)',
      quantity: 500,
      unit: 'liters',
      pricePerUnit: 55,
      description: 'Fresh cow milk, daily supply available. Clean and hygienic handling.',
      location: 'Embu',
      datePosted: new Date('2025-02-04'),
      status: 'available',
      image: '/images/farming/milk.jpg',
      createdAt: new Date('2025-02-04'),
      updatedAt: new Date('2025-02-04'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[9].id,
      farmerName: farmers[9].name,
      cropName: 'Passion Fruits',
      quantity: 150,
      unit: 'kg',
      pricePerUnit: 100,
      description: 'Purple passion fruits. Perfect for juice making. Very sweet.',
      location: 'Embu',
      datePosted: new Date('2025-02-03'),
      status: 'available',
      image: '/images/farming/passion_fruits.jpg',
      createdAt: new Date('2025-02-03'),
      updatedAt: new Date('2025-02-03'),
    },
    {
      id: uuidv4(),
      farmerId: farmers[9].id,
      farmerName: farmers[9].name,
      cropName: 'Kale (Sukuma Wiki)',
      quantity: 100,
      unit: 'kg',
      pricePerUnit: 25,
      description: 'Fresh organic kale, harvested daily. Very green and healthy.',
      location: 'Embu',
      datePosted: new Date('2025-02-02'),
      status: 'available',
      image: '/images/farming/kale.jpg',
      createdAt: new Date('2025-02-02'),
      updatedAt: new Date('2025-02-02'),
    },
  ];

  // Add demo buyers
  const buyers: User[] = [
    {
      id: uuidv4(),
      email: 'buyer1@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Michael Otieno',
      role: 'buyer',
      phone: '+254722111001',
      location: 'Nairobi',
      isVerified: true,
      verifiedAt: new Date('2025-01-10'),
      createdAt: new Date('2025-01-05'),
      updatedAt: new Date('2025-01-10'),
    },
    {
      id: uuidv4(),
      email: 'buyer2@example.com',
      password: await bcrypt.hash('password123', 10),
      name: 'Jane Mwende',
      role: 'buyer',
      phone: '+254722111002',
      location: 'Mombasa',
      isVerified: true,
      verifiedAt: new Date('2025-01-12'),
      createdAt: new Date('2025-01-08'),
      updatedAt: new Date('2025-01-12'),
    },
  ];

  // Admin user
  const admin: User = {
    id: uuidv4(),
    email: 'admin@umojahub.com',
    password: await bcrypt.hash('admin123', 10),
    name: 'Admin User',
    role: 'admin',
    phone: '+254700000000',
    location: 'Nairobi',
    isVerified: true,
    verifiedAt: new Date('2024-12-01'),
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  };

  // Add all users to database
  db.data.users = [...farmers, ...buyers, admin];
  db.data.cropListings = cropListings;

  await saveDb(db);

  console.log('✅ Demo data seeded successfully!');
  console.log(`   - ${farmers.length} farmers created`);
  console.log(`   - ${cropListings.length} crop listings created`);
  console.log(`   - ${buyers.length} buyers created`);
  console.log(`   - 1 admin user created`);
  console.log('\n📧 Test Credentials:');
  console.log('   Verified Farmer: john.kamau@example.com / password123');
  console.log('   Unverified Farmer: james.mutua@example.com / password123');
  console.log('   Buyer: buyer1@example.com / password123');
  console.log('   Admin: admin@umojahub.com / admin123');
}

seedDemoData()
  .then(() => {
    console.log('\n✨ Seeding completed successfully!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Error seeding data:', error);
    process.exit(1);
  });
